// Code generated by protoc-gen-go. DO NOT EDIT.
// source: location.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LocationItem struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocationItem) Reset()         { *m = LocationItem{} }
func (m *LocationItem) String() string { return proto.CompactTextString(m) }
func (*LocationItem) ProtoMessage()    {}
func (*LocationItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f0f35158dcf9f2c, []int{0}
}

func (m *LocationItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocationItem.Unmarshal(m, b)
}
func (m *LocationItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocationItem.Marshal(b, m, deterministic)
}
func (m *LocationItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocationItem.Merge(m, src)
}
func (m *LocationItem) XXX_Size() int {
	return xxx_messageInfo_LocationItem.Size(m)
}
func (m *LocationItem) XXX_DiscardUnknown() {
	xxx_messageInfo_LocationItem.DiscardUnknown(m)
}

var xxx_messageInfo_LocationItem proto.InternalMessageInfo

func (m *LocationItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type LocationRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocationRequest) Reset()         { *m = LocationRequest{} }
func (m *LocationRequest) String() string { return proto.CompactTextString(m) }
func (*LocationRequest) ProtoMessage()    {}
func (*LocationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f0f35158dcf9f2c, []int{1}
}

func (m *LocationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocationRequest.Unmarshal(m, b)
}
func (m *LocationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocationRequest.Marshal(b, m, deterministic)
}
func (m *LocationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocationRequest.Merge(m, src)
}
func (m *LocationRequest) XXX_Size() int {
	return xxx_messageInfo_LocationRequest.Size(m)
}
func (m *LocationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LocationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LocationRequest proto.InternalMessageInfo

func (m *LocationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LocationReply struct {
	Locations            *LocationItem `protobuf:"bytes,1,opt,name=locations,proto3" json:"locations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *LocationReply) Reset()         { *m = LocationReply{} }
func (m *LocationReply) String() string { return proto.CompactTextString(m) }
func (*LocationReply) ProtoMessage()    {}
func (*LocationReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f0f35158dcf9f2c, []int{2}
}

func (m *LocationReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocationReply.Unmarshal(m, b)
}
func (m *LocationReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocationReply.Marshal(b, m, deterministic)
}
func (m *LocationReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocationReply.Merge(m, src)
}
func (m *LocationReply) XXX_Size() int {
	return xxx_messageInfo_LocationReply.Size(m)
}
func (m *LocationReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LocationReply.DiscardUnknown(m)
}

var xxx_messageInfo_LocationReply proto.InternalMessageInfo

func (m *LocationReply) GetLocations() *LocationItem {
	if m != nil {
		return m.Locations
	}
	return nil
}

func init() {
	proto.RegisterType((*LocationItem)(nil), "proto.LocationItem")
	proto.RegisterType((*LocationRequest)(nil), "proto.LocationRequest")
	proto.RegisterType((*LocationReply)(nil), "proto.LocationReply")
}

func init() {
	proto.RegisterFile("location.proto", fileDescriptor_4f0f35158dcf9f2c)
}

var fileDescriptor_4f0f35158dcf9f2c = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0xc9, 0x4f, 0x4e,
	0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x72,
	0x5c, 0x3c, 0x3e, 0x50, 0x09, 0xcf, 0x92, 0xd4, 0x5c, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09,
	0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0xa6, 0xcc, 0x14, 0x25, 0x55, 0x2e, 0x7e, 0x98, 0x7c, 0x50,
	0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x10, 0x17, 0x4b, 0x5e, 0x62, 0x6e, 0x2a, 0x54, 0x11,
	0x98, 0xad, 0xe4, 0xc4, 0xc5, 0x8b, 0x50, 0x56, 0x90, 0x53, 0x29, 0x64, 0xc8, 0xc5, 0x09, 0xb3,
	0xb0, 0x18, 0xac, 0x92, 0xdb, 0x48, 0x18, 0x62, 0xb3, 0x1e, 0xb2, 0x7d, 0x41, 0x08, 0x55, 0x46,
	0xfe, 0x08, 0xab, 0x82, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0x6c, 0xb8, 0x78, 0xdc, 0x53,
	0x4b, 0x60, 0xa2, 0xc5, 0x42, 0x62, 0x68, 0x46, 0x40, 0x9d, 0x24, 0x25, 0x82, 0x21, 0x5e, 0x90,
	0x53, 0xe9, 0xc4, 0x19, 0xc5, 0xae, 0x67, 0x0d, 0x96, 0x48, 0x62, 0x03, 0x53, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x05, 0x56, 0xde, 0x41, 0x06, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LocationServiceClient is the client API for LocationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LocationServiceClient interface {
	GetLocations(ctx context.Context, in *LocationRequest, opts ...grpc.CallOption) (*LocationReply, error)
}

type locationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLocationServiceClient(cc grpc.ClientConnInterface) LocationServiceClient {
	return &locationServiceClient{cc}
}

func (c *locationServiceClient) GetLocations(ctx context.Context, in *LocationRequest, opts ...grpc.CallOption) (*LocationReply, error) {
	out := new(LocationReply)
	err := c.cc.Invoke(ctx, "/proto.LocationService/GetLocations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocationServiceServer is the server API for LocationService service.
type LocationServiceServer interface {
	GetLocations(context.Context, *LocationRequest) (*LocationReply, error)
}

// UnimplementedLocationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLocationServiceServer struct {
}

func (*UnimplementedLocationServiceServer) GetLocations(ctx context.Context, req *LocationRequest) (*LocationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLocations not implemented")
}

func RegisterLocationServiceServer(s *grpc.Server, srv LocationServiceServer) {
	s.RegisterService(&_LocationService_serviceDesc, srv)
}

func _LocationService_GetLocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).GetLocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.LocationService/GetLocations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).GetLocations(ctx, req.(*LocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LocationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.LocationService",
	HandlerType: (*LocationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLocations",
			Handler:    _LocationService_GetLocations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "location.proto",
}
